-- Rename model UI param profile IDs to capability-based template names.

UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-form-ratio-ref7' WHERE profile_id = 'gz-video-grok';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-form-ratio-frame-ref3' WHERE profile_id = 'gz-video-veo';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-form-ratio-ref7' WHERE profile_id = 'gz-video-omni-flash';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-form-ratio-audio-multi-ref' WHERE profile_id = 'gz-video-seedance';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-form-size-ref1' WHERE profile_id = 'gz-video-sora';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-form-ratio-ref4' WHERE profile_id = 'gz-video-kling';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-form-ratio-ref1-i2v' WHERE profile_id = 'gz-video-wan';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-json-15s-pro-audio-ref4v1a3' WHERE profile_id = 'gz-video-15s-pro';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-json-15s-fast-audio-ref4v1a1' WHERE profile_id = 'gz-video-15s-fast';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-json-10s-seed-ref9' WHERE profile_id = 'gz-video-10s';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-json-pro-audio-seed-ref4v1' WHERE profile_id = 'gz-video-muse-pro';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-json-fast-audio-seed-ref4v1' WHERE profile_id = 'gz-video-muse-fast';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-json-art-plain-ref4' WHERE profile_id = 'gz-video-plain';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-json-720-duration-ref4' WHERE profile_id = 'gz-video-sz';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-chat-i2v-ref1' WHERE profile_id = 'newapi-chat-wan-i2v';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-chat-no-params' WHERE profile_id = 'newapi-chat-sora';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-chat-fixed-4s' WHERE profile_id = 'newapi-chat-gemini-omni-flash-4s';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-chat-fixed-6s' WHERE profile_id = 'newapi-chat-gemini-omni-flash-6s';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-chat-fixed-10s' WHERE profile_id = 'newapi-chat-gemini-omni-flash-10s';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-chat-no-params' WHERE profile_id = 'newapi-chat-kling';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-gen-ratio-ref7' WHERE profile_id = 'newapi-grok-image-video';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-gen-ratio-ref1' WHERE profile_id = 'newapi-grok-video-1.5';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-no-params-orientation-fixed' WHERE profile_id = 'newapi-async-veo-fast-oriented';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-no-params-quality-fixed' WHERE profile_id = 'newapi-async-veo';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-ratio-frame-ref5' WHERE profile_id = 'oairegbox-omni-fast';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-v2v-ref1' WHERE profile_id = 'oairegbox-omni-v2v';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-v2v-clean' WHERE profile_id = 'oairegbox-veo-clean';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-ratio-duration-frame-ref9v3' WHERE profile_id = 'oairegbox-seedance-2';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-chat-ref7' WHERE profile_id = 'oairegbox-grok-imagine-video';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-ratio-duration-ref10v1' WHERE profile_id = 'oairegbox-grok-cli';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-ratio-ref1' WHERE profile_id = 'oairegbox-grok-cli-1.5';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-json-15s-pro-audio-ref4v1a3' WHERE profile_id = 'video-tpl-json-gz-15s-pro';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-json-15s-fast-audio-ref4v1a1' WHERE profile_id = 'video-tpl-json-gz-15s-fast';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-json-10s-seed-ref9' WHERE profile_id = 'video-tpl-json-gz-10s';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-json-pro-audio-seed-ref4v1' WHERE profile_id = 'video-tpl-json-gz-muse-pro';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-json-fast-audio-seed-ref4v1' WHERE profile_id = 'video-tpl-json-gz-muse-fast';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-json-art-plain-ref4' WHERE profile_id = 'video-tpl-json-gz-art-plain';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-json-720-duration-ref4' WHERE profile_id = 'video-tpl-json-gz-xinghe';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-chat-no-params' WHERE profile_id = 'video-tpl-chat-fixed-no-params';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-chat-fixed-4s' WHERE profile_id = 'video-tpl-chat-omni-flash-4s';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-chat-fixed-6s' WHERE profile_id = 'video-tpl-chat-omni-flash-6s';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-chat-fixed-10s' WHERE profile_id = 'video-tpl-chat-omni-flash-10s';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-no-params-orientation-fixed' WHERE profile_id = 'video-tpl-json-async-veo-orientation-fixed';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-no-params-quality-fixed' WHERE profile_id = 'video-tpl-json-async-veo-quality-fixed';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-ratio-frame-ref5' WHERE profile_id = 'video-tpl-json-async-omni-i2v-frame';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-v2v-ref1' WHERE profile_id = 'video-tpl-json-async-omni-v2v';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-v2v-clean' WHERE profile_id = 'video-tpl-json-async-veo-clean-v2v';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-ratio-duration-frame-ref9v3' WHERE profile_id = 'video-tpl-json-async-seedance-multi-ref';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-chat-ref7' WHERE profile_id = 'video-tpl-chat-grok-ref7';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-ratio-duration-ref10v1' WHERE profile_id = 'video-tpl-json-async-grok-cli';
UPDATE model_ui_param_profiles SET profile_id = 'video-tpl-async-ratio-ref1' WHERE profile_id = 'video-tpl-json-async-grok-cli-ref1';
UPDATE model_ui_param_profiles SET profile_id = 'image-tpl-aspect-count-extended' WHERE profile_id = 'image-tpl-aspect-count-gemini';
UPDATE model_ui_param_profiles SET profile_id = 'image-tpl-full-quality-export' WHERE profile_id = 'gz-image-2';
UPDATE model_ui_param_profiles SET profile_id = 'image-tpl-aspect-count-basic' WHERE profile_id = 'gpt-image-2';
UPDATE model_ui_param_profiles SET profile_id = 'image-tpl-aspect-count-extended' WHERE profile_id = 'gemini-image';
UPDATE model_ui_param_profiles SET profile_id = 'image-tpl-square-fixed-count' WHERE profile_id = 'grok-imagine-image';
UPDATE model_ui_param_profiles SET profile_id = 'image-tpl-square-4k-single' WHERE profile_id = 'gpt-image-2-4k';
UPDATE model_ui_param_profiles SET profile_id = 'image-tpl-aspect-count-extended' WHERE profile_id = 'image-tpl-aspect-count-gemini';

UPDATE models SET video_profile_id = 'video-tpl-form-ratio-ref7' WHERE video_profile_id = 'gz-video-grok';
UPDATE models SET video_profile_id = 'video-tpl-form-ratio-frame-ref3' WHERE video_profile_id = 'gz-video-veo';
UPDATE models SET video_profile_id = 'video-tpl-form-ratio-ref7' WHERE video_profile_id = 'gz-video-omni-flash';
UPDATE models SET video_profile_id = 'video-tpl-form-ratio-audio-multi-ref' WHERE video_profile_id = 'gz-video-seedance';
UPDATE models SET video_profile_id = 'video-tpl-form-size-ref1' WHERE video_profile_id = 'gz-video-sora';
UPDATE models SET video_profile_id = 'video-tpl-form-ratio-ref4' WHERE video_profile_id = 'gz-video-kling';
UPDATE models SET video_profile_id = 'video-tpl-form-ratio-ref1-i2v' WHERE video_profile_id = 'gz-video-wan';
UPDATE models SET video_profile_id = 'video-tpl-json-15s-pro-audio-ref4v1a3' WHERE video_profile_id = 'gz-video-15s-pro';
UPDATE models SET video_profile_id = 'video-tpl-json-15s-fast-audio-ref4v1a1' WHERE video_profile_id = 'gz-video-15s-fast';
UPDATE models SET video_profile_id = 'video-tpl-json-10s-seed-ref9' WHERE video_profile_id = 'gz-video-10s';
UPDATE models SET video_profile_id = 'video-tpl-json-pro-audio-seed-ref4v1' WHERE video_profile_id = 'gz-video-muse-pro';
UPDATE models SET video_profile_id = 'video-tpl-json-fast-audio-seed-ref4v1' WHERE video_profile_id = 'gz-video-muse-fast';
UPDATE models SET video_profile_id = 'video-tpl-json-art-plain-ref4' WHERE video_profile_id = 'gz-video-plain';
UPDATE models SET video_profile_id = 'video-tpl-json-720-duration-ref4' WHERE video_profile_id = 'gz-video-sz';
UPDATE models SET video_profile_id = 'video-tpl-chat-i2v-ref1' WHERE video_profile_id = 'newapi-chat-wan-i2v';
UPDATE models SET video_profile_id = 'video-tpl-chat-no-params' WHERE video_profile_id = 'newapi-chat-sora';
UPDATE models SET video_profile_id = 'video-tpl-chat-fixed-4s' WHERE video_profile_id = 'newapi-chat-gemini-omni-flash-4s';
UPDATE models SET video_profile_id = 'video-tpl-chat-fixed-6s' WHERE video_profile_id = 'newapi-chat-gemini-omni-flash-6s';
UPDATE models SET video_profile_id = 'video-tpl-chat-fixed-10s' WHERE video_profile_id = 'newapi-chat-gemini-omni-flash-10s';
UPDATE models SET video_profile_id = 'video-tpl-chat-no-params' WHERE video_profile_id = 'newapi-chat-kling';
UPDATE models SET video_profile_id = 'video-tpl-gen-ratio-ref7' WHERE video_profile_id = 'newapi-grok-image-video';
UPDATE models SET video_profile_id = 'video-tpl-gen-ratio-ref1' WHERE video_profile_id = 'newapi-grok-video-1.5';
UPDATE models SET video_profile_id = 'video-tpl-async-no-params-orientation-fixed' WHERE video_profile_id = 'newapi-async-veo-fast-oriented';
UPDATE models SET video_profile_id = 'video-tpl-async-no-params-quality-fixed' WHERE video_profile_id = 'newapi-async-veo';
UPDATE models SET video_profile_id = 'video-tpl-async-ratio-frame-ref5' WHERE video_profile_id = 'oairegbox-omni-fast';
UPDATE models SET video_profile_id = 'video-tpl-async-v2v-ref1' WHERE video_profile_id = 'oairegbox-omni-v2v';
UPDATE models SET video_profile_id = 'video-tpl-async-v2v-clean' WHERE video_profile_id = 'oairegbox-veo-clean';
UPDATE models SET video_profile_id = 'video-tpl-async-ratio-duration-frame-ref9v3' WHERE video_profile_id = 'oairegbox-seedance-2';
UPDATE models SET video_profile_id = 'video-tpl-chat-ref7' WHERE video_profile_id = 'oairegbox-grok-imagine-video';
UPDATE models SET video_profile_id = 'video-tpl-async-ratio-duration-ref10v1' WHERE video_profile_id = 'oairegbox-grok-cli';
UPDATE models SET video_profile_id = 'video-tpl-async-ratio-ref1' WHERE video_profile_id = 'oairegbox-grok-cli-1.5';
UPDATE models SET video_profile_id = 'video-tpl-json-15s-pro-audio-ref4v1a3' WHERE video_profile_id = 'video-tpl-json-gz-15s-pro';
UPDATE models SET video_profile_id = 'video-tpl-json-15s-fast-audio-ref4v1a1' WHERE video_profile_id = 'video-tpl-json-gz-15s-fast';
UPDATE models SET video_profile_id = 'video-tpl-json-10s-seed-ref9' WHERE video_profile_id = 'video-tpl-json-gz-10s';
UPDATE models SET video_profile_id = 'video-tpl-json-pro-audio-seed-ref4v1' WHERE video_profile_id = 'video-tpl-json-gz-muse-pro';
UPDATE models SET video_profile_id = 'video-tpl-json-fast-audio-seed-ref4v1' WHERE video_profile_id = 'video-tpl-json-gz-muse-fast';
UPDATE models SET video_profile_id = 'video-tpl-json-art-plain-ref4' WHERE video_profile_id = 'video-tpl-json-gz-art-plain';
UPDATE models SET video_profile_id = 'video-tpl-json-720-duration-ref4' WHERE video_profile_id = 'video-tpl-json-gz-xinghe';
UPDATE models SET video_profile_id = 'video-tpl-chat-no-params' WHERE video_profile_id = 'video-tpl-chat-fixed-no-params';
UPDATE models SET video_profile_id = 'video-tpl-chat-fixed-4s' WHERE video_profile_id = 'video-tpl-chat-omni-flash-4s';
UPDATE models SET video_profile_id = 'video-tpl-chat-fixed-6s' WHERE video_profile_id = 'video-tpl-chat-omni-flash-6s';
UPDATE models SET video_profile_id = 'video-tpl-chat-fixed-10s' WHERE video_profile_id = 'video-tpl-chat-omni-flash-10s';
UPDATE models SET video_profile_id = 'video-tpl-async-no-params-orientation-fixed' WHERE video_profile_id = 'video-tpl-json-async-veo-orientation-fixed';
UPDATE models SET video_profile_id = 'video-tpl-async-no-params-quality-fixed' WHERE video_profile_id = 'video-tpl-json-async-veo-quality-fixed';
UPDATE models SET video_profile_id = 'video-tpl-async-ratio-frame-ref5' WHERE video_profile_id = 'video-tpl-json-async-omni-i2v-frame';
UPDATE models SET video_profile_id = 'video-tpl-async-v2v-ref1' WHERE video_profile_id = 'video-tpl-json-async-omni-v2v';
UPDATE models SET video_profile_id = 'video-tpl-async-v2v-clean' WHERE video_profile_id = 'video-tpl-json-async-veo-clean-v2v';
UPDATE models SET video_profile_id = 'video-tpl-async-ratio-duration-frame-ref9v3' WHERE video_profile_id = 'video-tpl-json-async-seedance-multi-ref';
UPDATE models SET video_profile_id = 'video-tpl-chat-ref7' WHERE video_profile_id = 'video-tpl-chat-grok-ref7';
UPDATE models SET video_profile_id = 'video-tpl-async-ratio-duration-ref10v1' WHERE video_profile_id = 'video-tpl-json-async-grok-cli';
UPDATE models SET video_profile_id = 'video-tpl-async-ratio-ref1' WHERE video_profile_id = 'video-tpl-json-async-grok-cli-ref1';

UPDATE models SET image_profile_id = 'image-tpl-full-quality-export' WHERE image_profile_id = 'gz-image-2';
UPDATE models SET image_profile_id = 'image-tpl-aspect-count-basic' WHERE image_profile_id = 'gpt-image-2';
UPDATE models SET image_profile_id = 'image-tpl-aspect-count-extended' WHERE image_profile_id = 'gemini-image';
UPDATE models SET image_profile_id = 'image-tpl-square-fixed-count' WHERE image_profile_id = 'grok-imagine-image';
UPDATE models SET image_profile_id = 'image-tpl-square-4k-single' WHERE image_profile_id = 'gpt-image-2-4k';
UPDATE models SET image_profile_id = 'image-tpl-aspect-count-extended' WHERE image_profile_id = 'image-tpl-aspect-count-gemini';

UPDATE model_ui_param_profiles SET api_mode = 'videos-json-gz' WHERE profile_id = 'video-tpl-json-15s-pro-audio-ref4v1a3' AND (api_mode IS NULL OR api_mode = '');
UPDATE model_ui_param_profiles SET api_mode = 'videos-json-gz' WHERE profile_id = 'video-tpl-json-15s-fast-audio-ref4v1a1' AND (api_mode IS NULL OR api_mode = '');
UPDATE model_ui_param_profiles SET api_mode = 'videos-json-gz' WHERE profile_id = 'video-tpl-json-10s-seed-ref9' AND (api_mode IS NULL OR api_mode = '');
UPDATE model_ui_param_profiles SET api_mode = 'videos-json-gz' WHERE profile_id = 'video-tpl-json-pro-audio-seed-ref4v1' AND (api_mode IS NULL OR api_mode = '');
UPDATE model_ui_param_profiles SET api_mode = 'videos-json-gz' WHERE profile_id = 'video-tpl-json-fast-audio-seed-ref4v1' AND (api_mode IS NULL OR api_mode = '');
UPDATE model_ui_param_profiles SET api_mode = 'videos-json-gz' WHERE profile_id = 'video-tpl-json-art-plain-ref4' AND (api_mode IS NULL OR api_mode = '');
UPDATE model_ui_param_profiles SET api_mode = 'videos-json-gz' WHERE profile_id = 'video-tpl-json-720-duration-ref4' AND (api_mode IS NULL OR api_mode = '');

-- Merged into an existing template; models already point at the target profile.
DELETE FROM model_ui_param_profiles WHERE profile_id IN ('gz-video-omni-flash', 'newapi-chat-kling');
