/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.
*/

const CDN_BASE = (
  import.meta.env.VITE_STATIC_CDN || 'https://assets.cangyuansuanli.cn'
).replace(/\/$/, '')

export function siteAsset(path: string) {
  const normalized = path.startsWith('/') ? path : `/${path}`
  return `${CDN_BASE}${normalized}`
}

/**
 * Bundled with the app at /home/showcase.json (same-origin, no CORS).
 * Regenerated by scripts/generate-home-showcase.mjs; R2 upload is optional cache.
 */
export const SHOWCASE_MANIFEST_URL = '/home/showcase.json'

export const SITE_BRAND = {
  name: '沧元算力',
  logo: siteAsset('/site/logo.png'),
  domain: 'cangyuansuanli.cn',
} as const

export const INSPIRATION_SLIDES = [
  {
    id: '01',
    image: siteAsset('/home/inspiration/01-city-poster.jpg'),
    width: 1122,
    height: 1402,
    title: '城市文字旅行海报',
    tags: '海报 / 城市 / 排版',
  },
  {
    id: '02',
    image: siteAsset('/home/inspiration/02-portrait.jpg'),
    width: 941,
    height: 1672,
    title: '便利店写真人像',
    tags: '写真 / 人物 / 氛围',
  },
  {
    id: '03',
    image: siteAsset('/home/inspiration/03-product-blueprint.jpg'),
    width: 1086,
    height: 1448,
    title: '产品结构蓝图',
    tags: '产品 / 科技 / 蓝图',
  },
  {
    id: '04',
    image: siteAsset('/home/inspiration/04-campaign-kv.jpg'),
    width: 1080,
    height: 608,
    title: '视觉活动主 KV',
    tags: '商业 / 创意 / 风格',
  },
  {
    id: '05',
    image: siteAsset('/home/inspiration/05-celebrity-portrait.jpg'),
    width: 1200,
    height: 799,
    title: '写实名人肖像',
    tags: '摄影 / 人像 / 写实',
  },
  {
    id: '06',
    image: siteAsset('/home/inspiration/06-vr-headset-poster.jpg'),
    width: 800,
    height: 1200,
    title: 'VR 头显爆炸视图海报',
    tags: '海报 / 科技 / 产品',
  },
  {
    id: '07',
    image: siteAsset('/home/inspiration/07-food-map-illustration.jpg'),
    width: 1080,
    height: 1080,
    title: '手绘城市美食地图',
    tags: '插画 / 地图 / 美食',
  },
  {
    id: '08',
    image: siteAsset('/home/inspiration/08-quote-card-design.jpg'),
    width: 1200,
    height: 670,
    title: '双语引言卡片',
    tags: '排版 / 封面 / 文案',
  },
  {
    id: '09',
    image: siteAsset('/home/inspiration/09-doodle-product-ad.png'),
    width: 1024,
    height: 1536,
    title: '涂鸦创意产品广告',
    tags: '广告 / 手绘 / 创意',
  },
  {
    id: '10',
    image: siteAsset('/home/inspiration/10-claw-machine-scene.jpeg'),
    width: 600,
    height: 900,
    title: '潮玩抓娃娃机场景',
    tags: '商业 / 场景 / 潮玩',
  },
  {
    id: '11',
    image: siteAsset('/home/inspiration/11-ui-experiment.jpg'),
    width: 640,
    height: 480,
    title: '界面视觉实验',
    tags: '界面 / 科技 / 交互',
  },
] as const

function slideToShowcaseAsset(slide: (typeof INSPIRATION_SLIDES)[number]) {
  return {
    id: slide.id,
    image: slide.image,
    title: slide.title,
    tags: slide.tags,
    aspectRatio: slide.width / slide.height,
  }
}

/** Home marquee row A — inspiration 01–06 (fallback when prompt API unavailable) */
export const SHOWCASE_ROW_A = INSPIRATION_SLIDES.slice(0, 6).map(
  slideToShowcaseAsset
)

/** Home marquee row B — inspiration 07–11 (fallback only) */
export const SHOWCASE_ROW_B = INSPIRATION_SLIDES.slice(6).map(slideToShowcaseAsset)

export const SITE_ASSETS = {
  logo: SITE_BRAND.logo,
  tools: {
    claudeCode: siteAsset('/home/tools/claude-code.png'),
    codexCli: siteAsset('/home/tools/codex-cli.png'),
    geminiCli: siteAsset('/home/tools/gemini-cli.png'),
    imageApi: siteAsset('/home/tools/image-api.png'),
  },
} as const
